// Generated by StarDance
// https://github.com/Kxnrl

import { CSGearSlot, Instance } from "cs_script/point_script";

const HUD_LAYOUT_NAME = "hud_emoji_layout";
const BROADCAST_LAYOUT_NAME = "hud_emoji_broadcast_layout";
const HIDDEN_CLASS = "Hidden";
const COOLDOWN_SECONDS = 20;
const EMOJI_DISPLAY_SECONDS = 5;
const THINK_INTERVAL = 0.5;
const PICKUP_PAIR_WINDOW = 0.2;
const TEAM_T = 2;

const caseTexts = [
    "你个红蛋",
    "kaf",
    "达妮娅",
    "客服介入",
    "plogh",
    "羊",
    "太瞄啦",
];

const hudLayout = /** @type {import("cs_script/point_script").CustomHudLayout} */ (
    Instance.FindEntityByName(HUD_LAYOUT_NAME)
);
const broadcastLayout = /** @type {import("cs_script/point_script").CustomHudLayout} */ (
    Instance.FindEntityByName(BROADCAST_LAYOUT_NAME)
);

/** @type {number | undefined} */
let holderSlot;
let currentCase = caseTexts[0];
let cooldownReady = true;
let cooldownReadyTime = 0;
let lastCooldownText = "";
let activeEmojiIndex = -1;
let kafVisible = false;
let emojiHideTime = 0;
let kafHideTime = 0;
/** @type {import("cs_script/point_script").CSWeaponBase | undefined} */
let artifactWeapon;
/** @type {number | undefined} */
let pendingWeaponPickupSlot;
let pendingWeaponPickupTime = 0;
/** @type {{
 *     playerSlot: number,
 *     weapon: import("cs_script/point_script").CSWeaponBase,
 *     gameTime: number,
 * } | undefined} */
let lastWeaponPickup;

/** @param {import("cs_script/point_script").Entity | undefined} activator */
function findActivatorPlayer(activator) {
    for (const player of Instance.GetAllPlayerControllers()) {
        if (
            player === activator
            || player.GetPlayerPawn() === activator
            || player.GetObserverPawn() === activator
        ) {
            return player;
        }
    }

    return undefined;
}

/** @param {number} playerSlot */
function hideHud(playerSlot) {
    hudLayout.SetHasClassForPlayer(playerSlot, "emoji_hud", HIDDEN_CLASS, true);
}

function hideHudForAllPlayers() {
    for (const player of Instance.GetAllPlayerControllers()) {
        if (player.IsConnected()) {
            hideHud(player.GetPlayerSlot());
        }
    }
}

function clearHolder() {
    if (holderSlot !== undefined) {
        hideHud(holderSlot);
    }
    holderSlot = undefined;
    artifactWeapon = undefined;
    pendingWeaponPickupSlot = undefined;
    pendingWeaponPickupTime = 0;
}

/** @param {number} gameTime */
function validateHolder(gameTime) {
    if (holderSlot === undefined) {
        return;
    }

    const player = Instance.GetPlayerController(holderSlot);
    const pawn = player?.GetPlayerPawn();
    const waitingForWeapon = !artifactWeapon
        && pendingWeaponPickupSlot === holderSlot
        && gameTime - pendingWeaponPickupTime <= PICKUP_PAIR_WINDOW;
    const weaponOwnerSlot = artifactWeapon?.IsValid()
        ? artifactWeapon.GetOwner()?.GetPlayerController()?.GetPlayerSlot()
        : undefined;
    if (
        !player?.IsConnected()
        || !pawn?.IsValid()
        || pawn.GetHealth() <= 0
        || pawn.GetTeamNumber() === TEAM_T
        || (!waitingForWeapon && weaponOwnerSlot !== holderSlot)
    ) {
        clearHolder();
    }
}

/** @param {number} playerSlot */
function getRecentWeaponPickup(playerSlot) {
    if (
        !lastWeaponPickup
        || lastWeaponPickup.playerSlot !== playerSlot
        || Instance.GetGameTime() - lastWeaponPickup.gameTime > PICKUP_PAIR_WINDOW
    ) {
        return undefined;
    }

    return lastWeaponPickup;
}

/** @param {number} gameTime */
function getCooldownText(gameTime) {
    if (!cooldownReady && gameTime >= cooldownReadyTime) {
        cooldownReady = true;
    }

    return cooldownReady
        ? "已就绪"
        : `${Math.max(1, Math.ceil(cooldownReadyTime - gameTime))}秒`;
}

/**
 * @param {number} gameTime
 * @param {boolean} [force]
 */
function updateCooldown(gameTime, force = false) {
    const cooldownText = getCooldownText(gameTime);
    if (holderSlot !== undefined && (force || cooldownText !== lastCooldownText)) {
        hudLayout.SetDialogVariableStringForPlayer(holderSlot, "cooldown_value", "value", cooldownText);
        hudLayout.SetHasClassForPlayer(holderSlot, "cooldown_value", "Ready", cooldownReady);
    }

    lastCooldownText = cooldownText;
}

/** @param {number} playerSlot */
function showHud(playerSlot) {
    hudLayout.SetDialogVariableStringForPlayer(playerSlot, "case_value", "value", currentCase);
    hudLayout.SetHasClassForPlayer(playerSlot, "emoji_hud", HIDDEN_CLASS, false);
    updateCooldown(Instance.GetGameTime(), true);
}

/** @param {number} caseIndex */
function setCase(caseIndex) {
    currentCase = caseTexts[caseIndex];
    if (holderSlot !== undefined) {
        hudLayout.SetDialogVariableStringForPlayer(holderSlot, "case_value", "value", currentCase);
    }
}

function hideEmoji() {
    if (activeEmojiIndex >= 0) {
        broadcastLayout.SetHasClass(`emoji${activeEmojiIndex + 1}`, HIDDEN_CLASS, true);
    }

    broadcastLayout.SetHasClass("emoji_announcement", HIDDEN_CLASS, true);
    activeEmojiIndex = -1;
    emojiHideTime = 0;
}

/**
 * @param {number} emojiIndex
 * @param {number} gameTime
 */
function showEmoji(emojiIndex, gameTime) {
    if (activeEmojiIndex >= 0 && activeEmojiIndex !== emojiIndex) {
        broadcastLayout.SetHasClass(`emoji${activeEmojiIndex + 1}`, HIDDEN_CLASS, true);
    }

    activeEmojiIndex = emojiIndex;
    emojiHideTime = gameTime + EMOJI_DISPLAY_SECONDS;
    broadcastLayout.SetHasClass(`emoji${emojiIndex + 1}`, HIDDEN_CLASS, false);
    broadcastLayout.SetHasClass("emoji_announcement", HIDDEN_CLASS, false);
}

function hideKaf() {
    broadcastLayout.SetHasClass("kaf", HIDDEN_CLASS, true);
    kafVisible = false;
    kafHideTime = 0;
}

/** @param {number} gameTime */
function showKaf(gameTime) {
    broadcastLayout.SetHasClass("kaf", HIDDEN_CLASS, false);
    kafVisible = true;
    kafHideTime = gameTime + EMOJI_DISPLAY_SECONDS;
}

/** @param {number} caseIndex */
function useCase(caseIndex) {
    const gameTime = Instance.GetGameTime();
    setCase(caseIndex);
    cooldownReady = false;
    cooldownReadyTime = gameTime + COOLDOWN_SECONDS;
    updateCooldown(gameTime, true);
    showEmoji(caseIndex, gameTime);
}

function resetHud() {
    holderSlot = undefined;
    currentCase = caseTexts[0];
    cooldownReady = true;
    cooldownReadyTime = 0;
    lastCooldownText = "";
    hideEmoji();
    artifactWeapon = undefined;
    pendingWeaponPickupSlot = undefined;
    pendingWeaponPickupTime = 0;
    lastWeaponPickup = undefined;

    for (let index = 0; index < caseTexts.length; index += 1) {
        broadcastLayout.SetHasClass(`emoji${index + 1}`, HIDDEN_CLASS, true);
    }

    hideHudForAllPlayers();
}

Instance.SetThink(() => {
    const gameTime = Instance.GetGameTime();
    validateHolder(gameTime);
    if (holderSlot !== undefined) {
        updateCooldown(gameTime);
    }
    if (activeEmojiIndex >= 0 && gameTime >= emojiHideTime) {
        hideEmoji();
    }
    if (kafVisible && gameTime >= kafHideTime) {
        hideKaf();
    }

    Instance.SetNextThink(gameTime + THINK_INTERVAL);
});

Instance.OnActivate(() => {
    resetHud();
    hideKaf();
    Instance.SetNextThink(Instance.GetGameTime() + THINK_INTERVAL);
});

Instance.OnRoundStart(() => {
    resetHud();
    hideKaf();
});

Instance.OnPlayerDisconnect(({ playerSlot }) => {
    if (holderSlot === playerSlot) {
        clearHolder();
    }
});

Instance.OnScriptInput("pickup", ({ activator }) => {
    const player = findActivatorPlayer(activator);
    if (!player) {
        return;
    }

    const nextHolderSlot = player.GetPlayerSlot();
    if (holderSlot !== undefined && holderSlot !== nextHolderSlot) {
        hideHud(holderSlot);
    }

    holderSlot = nextHolderSlot;
    const recentPickup = getRecentWeaponPickup(nextHolderSlot);
    artifactWeapon = recentPickup?.weapon;
    pendingWeaponPickupSlot = recentPickup ? undefined : nextHolderSlot;
    pendingWeaponPickupTime = recentPickup ? 0 : Instance.GetGameTime();
    showHud(nextHolderSlot);
});

Instance.OnWeaponPickup(({ weapon }) => {
    if (weapon.GetData().GetGearSlot() !== CSGearSlot.PISTOL) {
        return;
    }

    const controller = weapon.GetOwner()?.GetPlayerController();
    if (!controller) {
        return;
    }

    const playerSlot = controller.GetPlayerSlot();
    lastWeaponPickup = {
        playerSlot,
        weapon,
        gameTime: Instance.GetGameTime(),
    };

    if (pendingWeaponPickupSlot === playerSlot) {
        artifactWeapon = weapon;
        pendingWeaponPickupSlot = undefined;
        pendingWeaponPickupTime = 0;
    }
});

Instance.OnWeaponDrop(({ weapon }) => {
    if (weapon !== artifactWeapon) {
        return;
    }

    clearHolder();
});

for (let index = 0; index < caseTexts.length; index += 1) {
    Instance.OnScriptInput(`case${index + 1}`, () => {
        setCase(index);
    });

    Instance.OnScriptInput(`use${index + 1}`, () => {
        useCase(index);
    });
}

Instance.OnScriptInput("kaf", () => {
    showKaf(Instance.GetGameTime());
});
