// Generated by StarDance
// https://github.com/Kxnrl

import { Instance } from "cs_script/point_script";

const HUD_LAYOUT_NAME = "hud_kiki_layout";
const ENERGY_COUNTER_NAME = "template_kiki_math_counter";
const ULTI_COUNTER_NAME = "template_kiki_ulti_counter";
const HIDDEN_CLASS = "Hidden";
const POLL_INTERVAL = 0.5;
const SHIELD_COOLDOWN = 10;
const PICKUP_PAIR_WINDOW = 0.2;
const TEAM_T = 2;

const skillTexts = [
    "推力(对僵尸生效)",
    "推力(对人类生效)",
    "永恒记忆(200能量)",
    "范围治疗(150能量)",
    "恢复(蹲下充能)",
];

const hudLayout = /** @type {import("cs_script/point_script").CustomHudLayout} */ (
    Instance.FindEntityByName(HUD_LAYOUT_NAME)
);

/** @type {number | undefined} */
let holderSlot;
let currentSkill = "—";
let currentSkillIndex = -1;
let currentEnergy = "0";
let currentUltiCount = 0;
let shieldReady = true;
let shieldReadyTime = 0;
let lastShieldText = "";
/** @type {import("cs_script/point_script").CSWeaponBase | undefined} */
let artifactWeapon;
/** @type {number | undefined} */
let pendingWeaponPickupSlot;
let pendingWeaponPickupTime = 0;
/** @type {{
 *     playerSlot: number,
 *     weapon: import("cs_script/point_script").CSWeaponBase,
 *     gameTime: number,
 * } | undefined} */
let lastWeaponPickup;

/** @type {Set<import("cs_script/point_script").Entity>} */
const connectedCounters = new Set();
/** @type {Set<import("cs_script/point_script").Entity>} */
const connectedUltiCounters = new Set();

/** @param {import("cs_script/point_script").Entity | undefined} activator */
function findActivatorPlayer(activator) {
    for (const player of Instance.GetAllPlayerControllers()) {
        if (
            player === activator
            || player.GetPlayerPawn() === activator
            || player.GetObserverPawn() === activator
        ) {
            return player;
        }
    }

    return undefined;
}

/** @param {number} playerSlot */
function showHud(playerSlot) {
    hudLayout.SetDialogVariableStringForPlayer(playerSlot, "skill_value", "value", currentSkill);
    hudLayout.SetDialogVariableStringForPlayer(playerSlot, "energy_value", "value", currentEnergy);
    hudLayout.SetHasClassForPlayer(playerSlot, "kiki_hud", HIDDEN_CLASS, false);
    updateUltiVisibility();
    updateShield(Instance.GetGameTime(), true);
}

/** @param {number} playerSlot */
function hideHud(playerSlot) {
    hudLayout.SetHasClassForPlayer(playerSlot, "kiki_hud", HIDDEN_CLASS, true);
}

function clearHolder() {
    if (holderSlot !== undefined) {
        hideHud(holderSlot);
    }
    holderSlot = undefined;
    artifactWeapon = undefined;
    pendingWeaponPickupSlot = undefined;
    pendingWeaponPickupTime = 0;
}

/** @param {number} playerSlot */
function getRecentWeaponPickup(playerSlot) {
    if (
        !lastWeaponPickup
        || lastWeaponPickup.playerSlot !== playerSlot
        || Instance.GetGameTime() - lastWeaponPickup.gameTime > PICKUP_PAIR_WINDOW
    ) {
        return undefined;
    }

    return lastWeaponPickup;
}

/** @param {number} gameTime */
function validateHolder(gameTime) {
    if (holderSlot === undefined) {
        return;
    }

    const player = Instance.GetPlayerController(holderSlot);
    const pawn = player?.GetPlayerPawn();
    const waitingForWeapon = !artifactWeapon
        && pendingWeaponPickupSlot === holderSlot
        && gameTime - pendingWeaponPickupTime <= PICKUP_PAIR_WINDOW;
    const weaponOwnerSlot = artifactWeapon?.IsValid()
        ? artifactWeapon.GetOwner()?.GetPlayerController()?.GetPlayerSlot()
        : undefined;
    if (
        !player?.IsConnected()
        || !pawn?.IsValid()
        || pawn.GetHealth() <= 0
        || pawn.GetTeamNumber() === TEAM_T
        || (!waitingForWeapon && weaponOwnerSlot !== holderSlot)
    ) {
        clearHolder();
    }
}

/** @param {number} skillIndex */
function setSkill(skillIndex) {
    currentSkillIndex = skillIndex;
    currentSkill = skillTexts[skillIndex];
    if (holderSlot !== undefined) {
        hudLayout.SetDialogVariableStringForPlayer(holderSlot, "skill_value", "value", currentSkill);
        updateUltiVisibility();
    }
}

function updateUltiVisibility() {
    if (holderSlot === undefined) {
        return;
    }

    const visible = currentSkillIndex === 2;
    hudLayout.SetHasClassForPlayer(holderSlot, "ulti_progress", HIDDEN_CLASS, !visible);

    for (let index = 0; index < 4; index += 1) {
        hudLayout.SetHasClassForPlayer(
            holderSlot,
            `ulti_box_${index + 1}`,
            "Filled",
            visible && index < currentUltiCount,
        );
    }
}

/**
 * @param {number} gameTime
 * @param {boolean} [force]
 */
function updateShield(gameTime, force = false) {
    if (!shieldReady && gameTime >= shieldReadyTime) {
        shieldReady = true;
    }

    const shieldText = shieldReady
        ? "已就绪"
        : `${Math.max(1, Math.ceil(shieldReadyTime - gameTime))}秒`;

    if (holderSlot !== undefined && (force || shieldText !== lastShieldText)) {
        hudLayout.SetDialogVariableStringForPlayer(holderSlot, "shield_value", "value", shieldText);
        hudLayout.SetHasClassForPlayer(holderSlot, "shield_value", "Ready", shieldReady);
    }

    lastShieldText = shieldText;
}

/** @param {import("cs_script/point_script").InputValue | undefined} value */
function updateEnergy(value) {
    if (value === undefined) {
        return;
    }

    const nextEnergy = String(value);
    if (nextEnergy === currentEnergy) {
        return;
    }

    currentEnergy = nextEnergy;
    if (holderSlot !== undefined) {
        hudLayout.SetDialogVariableStringForPlayer(holderSlot, "energy_value", "value", currentEnergy);
    }
}

function connectEnergyCounters() {
    for (const counter of Instance.FindEntitiesByName(ENERGY_COUNTER_NAME)) {
        if (connectedCounters.has(counter)) {
            continue;
        }

        const connectionId = Instance.ConnectOutput(counter, "OnGetValue", ({ value }) => {
            updateEnergy(value);
        });

        if (connectionId !== undefined) {
            connectedCounters.add(counter);
        }
    }
}

function pollEnergy() {
    connectEnergyCounters();
    Instance.EntFireAtName({
        name: ENERGY_COUNTER_NAME,
        input: "GetValue",
    });
}

function connectUltiCounters() {
    for (const counter of Instance.FindEntitiesByName(ULTI_COUNTER_NAME)) {
        if (connectedUltiCounters.has(counter)) {
            continue;
        }

        const connectionId = Instance.ConnectOutput(counter, "OnGetValue", ({ value }) => {
            if (value === undefined) {
                return;
            }

            const parsedValue = Number(value);
            if (!Number.isFinite(parsedValue)) {
                return;
            }

            currentUltiCount = Math.max(0, Math.min(4, Math.floor(parsedValue)));
            updateUltiVisibility();
        });

        if (connectionId !== undefined) {
            connectedUltiCounters.add(counter);
        }
    }
}

function pollUltiCounter() {
    connectUltiCounters();
    Instance.EntFireAtName({
        name: ULTI_COUNTER_NAME,
        input: "GetValue",
    });
}

function resetHud() {
    holderSlot = undefined;
    currentSkill = "—";
    currentSkillIndex = -1;
    currentEnergy = "0";
    currentUltiCount = 0;
    shieldReady = true;
    shieldReadyTime = 0;
    lastShieldText = "";
    artifactWeapon = undefined;
    pendingWeaponPickupSlot = undefined;
    pendingWeaponPickupTime = 0;
    lastWeaponPickup = undefined;

    for (const player of Instance.GetAllPlayerControllers()) {
        if (player.IsConnected()) {
            hideHud(player.GetPlayerSlot());
        }
    }
}

Instance.SetThink(() => {
    const gameTime = Instance.GetGameTime();
    validateHolder(gameTime);

    if (holderSlot !== undefined) {
        updateShield(gameTime);
        pollEnergy();
        pollUltiCounter();
    }

    Instance.SetNextThink(gameTime + POLL_INTERVAL);
});

Instance.OnActivate(() => {
    resetHud();
    connectEnergyCounters();
    connectUltiCounters();
    Instance.SetNextThink(Instance.GetGameTime() + POLL_INTERVAL);
});

Instance.OnRoundStart(() => {
    resetHud();
});

Instance.OnPlayerDisconnect(({ playerSlot }) => {
    if (holderSlot === playerSlot) {
        clearHolder();
    }
});

Instance.OnScriptInput("pickup", ({ activator }) => {
    const player = findActivatorPlayer(activator);
    if (!player) {
        return;
    }

    const nextHolderSlot = player.GetPlayerSlot();
    if (holderSlot !== undefined && holderSlot !== nextHolderSlot) {
        hideHud(holderSlot);
    }

    holderSlot = nextHolderSlot;
    const recentPickup = getRecentWeaponPickup(nextHolderSlot);
    artifactWeapon = recentPickup?.weapon;
    pendingWeaponPickupSlot = recentPickup ? undefined : nextHolderSlot;
    pendingWeaponPickupTime = recentPickup ? 0 : Instance.GetGameTime();
    showHud(nextHolderSlot);
    pollEnergy();
});

Instance.OnWeaponPickup(({ weapon }) => {
    if (!weapon.GetClassName().includes("knife")) {
        return;
    }

    const controller = weapon.GetOwner()?.GetPlayerController();
    if (!controller) {
        return;
    }

    const playerSlot = controller.GetPlayerSlot();
    lastWeaponPickup = {
        playerSlot,
        weapon,
        gameTime: Instance.GetGameTime(),
    };
    if (pendingWeaponPickupSlot === playerSlot) {
        artifactWeapon = weapon;
        pendingWeaponPickupSlot = undefined;
        pendingWeaponPickupTime = 0;
    }
});

Instance.OnWeaponDrop(({ weapon }) => {
    if (weapon === artifactWeapon) {
        clearHolder();
    }
});

for (let index = 0; index < skillTexts.length; index += 1) {
    Instance.OnScriptInput(`skill${index + 1}`, () => {
        setSkill(index);
    });
}

Instance.OnScriptInput("shielduse", () => {
    if (!shieldReady) {
        return;
    }

    shieldReady = false;
    shieldReadyTime = Instance.GetGameTime() + SHIELD_COOLDOWN;
    updateShield(Instance.GetGameTime(), true);
});
