// Generated by StarDance
// https://github.com/Kxnrl

import { Instance } from "cs_script/point_script";

const HIDDEN_CLASS = "Hidden";
const LOCKED_CLASS = "Locked";

const stories = [
    {
        title: "基本讯息",
        body: [
            `基本讯息
编号:001
性别:女
年龄:未知
描述:拥有著最后的白巫女之称的女孩，能净化所有污秽
近期发现能召唤暗影高达`,
            `基本讯息
编号:213
性别:女
年龄:17
描述:粉色头发的女孩，力气非常大`,
            `基本讯息
编号:842
性别:女
年龄:16
描述:除了情绪多样化无任何特殊能力`,
        ].join("\n\n"),
    },
    {
        title: "研究员的笔记2",
        body: [
            `22xx/1/26/18:24
Karl:下水道已经全是它们的地盘了
为了防止更多人受到伤害
我必须赶紧关闭三个核心
用紧急对策系统来消灭它们`,
            "我必...得逃...去..通知...",
        ].join("\n\n"),
    },
    {
        title: "小女孩的日记",
        body: [
            `22xx/7/4
听说只要满十岁就会被接走
虽然离开孤儿院的大家会有点寂寞
但是我相信未来还能在与他们相见`,
            `22xx/11/14
今天有一位叔叔把我给接走了
即使知道离开的时间将至
但是与他们分别的时候我还是哭的很伤心`,
            `22xx/11/20
安顿好后叔叔带我去买新衣服
还带我去吃大餐
为我安排了家庭教师
说著什么要将我培养成一位合格的向导`,
        ].join("\n\n"),
    },
    {
        title: "小女孩的日记2",
        body: [
            `22xx/1/11
今天是我的生日
爸爸说了回来的时候会帮我带上蛋糕
以及从孤儿院寄来的信
说是大家寄给我的
好期待阿~`,
            `22xx/1/12
爸爸怎么还没回来?
是因为工作太忙忘记了吗...
明天就要去寄宿学院了
希望他平安无事`,
        ].join("\n\n"),
    },
    {
        title: "Kiki的发圈",
        body: [
            "(看起来已经在这个角落很久了，有些许的泛黄)",
            "(被女孩作为护身符赠送给父亲的发圈)",
        ].join("\n\n"),
    },
    {
        title: "助理纸条",
        body: [
            `躲在这里应该是安全的....
为什么所长要做这种研究
当时我们就应该的Karl的劝戒
即使这里已经不再被重视
也不应该为了这种是冒大险`,
            `拜托了....谁来救救我
这里好可怕
外面都是未知的怪物`,
            "不要...放开我...拜托不要!!!",
        ].join("\n\n"),
    },
    {
        title: "对话记录1",
        body: `Karl:所长，拜托停下这个研究吧
我们再想想有什么办法
这个实在是太危险了
我们不知道这个传送门会通往哪里?
也许对面有著我们未知的生命体

Brand:我们哪有那种时间
这里再不拿出些研究成果
总是被其他研究所嘲讽是饭桶
你知道每次大集合的时候，那一双双冰冷冷的眼睛看著我
是什么感觉吗?
我再说一遍，让开!不要阻止我`,
    },
    {
        title: "对话记录2",
        body: [
            `助理:所长...Karl他已经一个礼拜没来研究所了....
Brand:不用管那个不知道此价值为何的人
我们的实验已经快成功了
到时候这所有的荣耀都将归于我`,
            `Brand:我们的研究所将会获得前所未有的光荣
跟随我的你们也将会获得所有人崇拜的目光
明天....只要模拟完我们就能成为真正的@#!$%`,
        ].join("\n\n"),
    },
    {
        title: "研究员的笔记1",
        body: [
            `Karl:没办法了...既然劝不动所长
我也只能尽力让这次的实验能够安全结束`,
            `Karl:有了!只要将这些数值调整成这样
再加入一些程式
我想传送门就能变得稳定多了
已经过去了一个礼拜了吗?
我得赶紧回到研究所去告诉所长
希望在那之前他不要做什么傻事...`,
        ].join("\n\n"),
    },
    {
        title: "传送门安全程序",
        body: "(没有,作者想不到怎么给这东西加叙述,我也不是学理的,投降)",
    },
];

const unlockedStories = Array(stories.length).fill(false);
const hudLayout = /** @type {import("cs_script/point_script").CustomHudLayout} */ (
    Instance.FindEntityByName("hud_story_layout")
);

/** @param {number} value */
function twoDigits(value) {
    return String(value).padStart(2, "0");
}

/** @param {import("cs_script/point_script").Entity | undefined} activator */
function findActivatorPlayer(activator) {
    for (const player of Instance.GetAllPlayerControllers()) {
        if (
            player === activator
            || player.GetPlayerPawn() === activator
            || player.GetObserverPawn() === activator
        ) {
            return player;
        }
    }

    return undefined;
}

function updateStoryList() {
    for (let index = 0; index < stories.length; index += 1) {
        const story = stories[index];
        const suffix = twoDigits(index + 1);
        const buttonId = `story_button_${suffix}`;
        const titleId = `story_title_${suffix}`;

        hudLayout.SetHasClass(buttonId, LOCKED_CLASS, !unlockedStories[index]);
        hudLayout.SetDialogVariableString(titleId, "title", unlockedStories[index] ? story.title : "???");
    }
}

/** @param {number} playerSlot */
function showStoryList(playerSlot) {
    updateStoryList();
    hudLayout.SetHasClassForPlayer(playerSlot, "story_dialog", HIDDEN_CLASS, false);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_list", HIDDEN_CLASS, false);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_detail", HIDDEN_CLASS, true);
    hudLayout.SetInputCaptureEnabled(playerSlot, true);
}

/**
 * @param {number} playerSlot
 * @param {{ title: string, body: string }} story
 */
function showStoryDetail(playerSlot, story) {
    hudLayout.SetDialogVariableStringForPlayer(playerSlot, "detail_title", "title", story.title);
    hudLayout.SetDialogVariableStringForPlayer(playerSlot, "detail_body", "body", story.body);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_list", HIDDEN_CLASS, true);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_detail", HIDDEN_CLASS, false);
}

/** @param {number} playerSlot */
function hideHud(playerSlot) {
    hudLayout.SetHasClassForPlayer(playerSlot, "story_dialog", HIDDEN_CLASS, true);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_list", HIDDEN_CLASS, false);
    hudLayout.SetHasClassForPlayer(playerSlot, "story_detail", HIDDEN_CLASS, true);
    hudLayout.SetInputCaptureEnabled(playerSlot, false);
}

/** @param {number} index */
function unlockStory(index) {
    unlockedStories[index] = true;
    updateStoryList();
}

Instance.OnActivate(() => {
    updateStoryList();
});

Instance.OnRoundStart(() => {
    unlockedStories.fill(false);
    updateStoryList();

    for (const player of Instance.GetAllPlayerControllers()) {
        if (player.IsConnected()) {
            hideHud(player.GetPlayerSlot());
        }
    }
});

Instance.OnScriptInput("OpenHud", ({ activator }) => {
    const player = findActivatorPlayer(activator);
    if (!player) {
        return;
    }

    showStoryList(player.GetPlayerSlot());
});

for (let index = 0; index < stories.length; index += 1) {
    Instance.OnScriptInput(`Unlock${twoDigits(index + 1)}`, () => {
        unlockStory(index);
    });
}

Instance.OnCustomHudClicked(({ player, layout, buttonId }) => {
    if (layout !== hudLayout) {
        return;
    }

    const playerSlot = player.GetPlayerSlot();

    if (buttonId === "close_button") {
        hideHud(playerSlot);
        return;
    }

    if (buttonId === "back_button") {
        showStoryList(playerSlot);
        return;
    }

    const match = /^story_button_(\d{2})$/.exec(buttonId);
    if (!match) {
        return;
    }

    const storyIndex = Number(match[1]) - 1;
    const story = stories[storyIndex];
    if (!story || !unlockedStories[storyIndex]) {
        return;
    }

    showStoryDetail(playerSlot, story);
});
